#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib.sh"
gcp_defaults
require_env HEAD_DEVELOPER_API_IMAGE_URI

SERVICE_NAME="${HEAD_DEVELOPER_CLOUD_RUN_SERVICE:-head-developer-api}"
CONTROL_SA="$(sa_email "${HEAD_DEVELOPER_CONTROL_PLANE_SA}")"
MIN_INSTANCES="${HEAD_DEVELOPER_CLOUD_RUN_MIN_INSTANCES:-1}"
MAX_INSTANCES="${HEAD_DEVELOPER_CLOUD_RUN_MAX_INSTANCES:-5}"
CONCURRENCY="${HEAD_DEVELOPER_CLOUD_RUN_CONCURRENCY:-1}"
ENV_VARS="HEAD_DEVELOPER_ENV=${HEAD_DEVELOPER_ENV},GCP_PROJECT_ID=${GCP_PROJECT_ID},GCP_REGION=${GCP_REGION}"

if [[ -n "${HEAD_DEVELOPER_CODEX_AUTH_METHOD:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_AUTH_METHOD=${HEAD_DEVELOPER_CODEX_AUTH_METHOD}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_HOME:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_HOME=${HEAD_DEVELOPER_CODEX_HOME}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET=${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET_PROJECT:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET_PROJECT=${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET_PROJECT}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET_VERSION:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET_VERSION=${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_SECRET_VERSION}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_GCS_URI:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_HOME_BUNDLE_GCS_URI=${HEAD_DEVELOPER_CODEX_HOME_BUNDLE_GCS_URI}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_API_KEY_SECRET:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_API_KEY_SECRET=${HEAD_DEVELOPER_CODEX_API_KEY_SECRET}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_API_KEY_SECRET_PROJECT:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_API_KEY_SECRET_PROJECT=${HEAD_DEVELOPER_CODEX_API_KEY_SECRET_PROJECT}"
fi
if [[ -n "${HEAD_DEVELOPER_CODEX_API_KEY_SECRET_VERSION:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_CODEX_API_KEY_SECRET_VERSION=${HEAD_DEVELOPER_CODEX_API_KEY_SECRET_VERSION}"
fi
if [[ -n "${HEAD_DEVELOPER_WORKER_IMAGE_URI:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_WORKER_IMAGE_URI=${HEAD_DEVELOPER_WORKER_IMAGE_URI}"
fi
if [[ -n "${SUPERVISOR_MODEL_PROVIDER:-}" ]]; then
  ENV_VARS="${ENV_VARS},SUPERVISOR_MODEL_PROVIDER=${SUPERVISOR_MODEL_PROVIDER}"
fi
if [[ -n "${VERTEX_PROJECT_ID:-}" ]]; then
  ENV_VARS="${ENV_VARS},VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID}"
fi
if [[ -n "${VERTEX_LOCATION:-}" ]]; then
  ENV_VARS="${ENV_VARS},VERTEX_LOCATION=${VERTEX_LOCATION}"
fi
if [[ -n "${VERTEX_MODEL:-}" ]]; then
  ENV_VARS="${ENV_VARS},VERTEX_MODEL=${VERTEX_MODEL}"
fi
if [[ -n "${WORKER_MODE:-}" ]]; then
  ENV_VARS="${ENV_VARS},WORKER_MODE=${WORKER_MODE}"
fi
if [[ -n "${DEFAULT_WORKER_MODE:-}" ]]; then
  ENV_VARS="${ENV_VARS},DEFAULT_WORKER_MODE=${DEFAULT_WORKER_MODE}"
fi
if [[ -n "${HEAD_DEVELOPER_DEFAULT_WORKER_TYPE:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_DEFAULT_WORKER_TYPE=${HEAD_DEVELOPER_DEFAULT_WORKER_TYPE}"
fi
if [[ -n "${HEAD_DEVELOPER_API_CALLBACK_URL:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_API_CALLBACK_URL=${HEAD_DEVELOPER_API_CALLBACK_URL}"
fi
if [[ -n "${CODEX_PHONE_SUPERVISOR_PUBLIC_BASE_URL:-}" ]]; then
  ENV_VARS="${ENV_VARS},CODEX_PHONE_SUPERVISOR_PUBLIC_BASE_URL=${CODEX_PHONE_SUPERVISOR_PUBLIC_BASE_URL}"
elif [[ -n "${HEAD_DEVELOPER_API_CALLBACK_URL:-}" ]]; then
  ENV_VARS="${ENV_VARS},CODEX_PHONE_SUPERVISOR_PUBLIC_BASE_URL=${HEAD_DEVELOPER_API_CALLBACK_URL}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_CLUSTER_NAME:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_CLUSTER_NAME=${HEAD_DEVELOPER_GKE_CLUSTER_NAME}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_LOCATION:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_LOCATION=${HEAD_DEVELOPER_GKE_LOCATION}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_NAMESPACE:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_NAMESPACE=${HEAD_DEVELOPER_GKE_NAMESPACE}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_KSA:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_KSA=${HEAD_DEVELOPER_GKE_KSA}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_GSA:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_GSA=${HEAD_DEVELOPER_GKE_GSA}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_JOB_TTL_SECONDS:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_JOB_TTL_SECONDS=${HEAD_DEVELOPER_GKE_JOB_TTL_SECONDS}"
fi
if [[ -n "${HEAD_DEVELOPER_GKE_JOB_ACTIVE_DEADLINE_SECONDS:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_GKE_JOB_ACTIVE_DEADLINE_SECONDS=${HEAD_DEVELOPER_GKE_JOB_ACTIVE_DEADLINE_SECONDS}"
fi
if [[ -n "${MAX_GKE_JOB_WORKERS:-}" ]]; then
  ENV_VARS="${ENV_VARS},MAX_GKE_JOB_WORKERS=${MAX_GKE_JOB_WORKERS}"
fi
if [[ -n "${HEAD_DEVELOPER_STATE_STORE:-}" ]]; then
  ENV_VARS="${ENV_VARS},HEAD_DEVELOPER_STATE_STORE=${HEAD_DEVELOPER_STATE_STORE}"
fi
if [[ -n "${FIRESTORE_PROJECT_ID:-}" ]]; then
  ENV_VARS="${ENV_VARS},FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}"
fi
if [[ -n "${FIRESTORE_DATABASE_ID:-}" ]]; then
  ENV_VARS="${ENV_VARS},FIRESTORE_DATABASE_ID=${FIRESTORE_DATABASE_ID}"
fi
if [[ -n "${FIRESTORE_COLLECTION_PREFIX:-}" ]]; then
  ENV_VARS="${ENV_VARS},FIRESTORE_COLLECTION_PREFIX=${FIRESTORE_COLLECTION_PREFIX}"
fi
if [[ -n "${FIRESTORE_STATE_OPERATION_TIMEOUT_MS:-}" ]]; then
  ENV_VARS="${ENV_VARS},FIRESTORE_STATE_OPERATION_TIMEOUT_MS=${FIRESTORE_STATE_OPERATION_TIMEOUT_MS}"
fi

echo "Deploying Cloud Run service ${SERVICE_NAME} with authentication required..."
gcloud run deploy "${SERVICE_NAME}" \
  --project="${GCP_PROJECT_ID}" \
  --region="${GCP_REGION}" \
  --image="${HEAD_DEVELOPER_API_IMAGE_URI}" \
  --service-account="${CONTROL_SA}" \
  --min-instances="${MIN_INSTANCES}" \
  --max-instances="${MAX_INSTANCES}" \
  --concurrency="${CONCURRENCY}" \
  --no-allow-unauthenticated \
  --update-env-vars="${ENV_VARS}" \
  --labels="$(label_args)"
