import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

test("dashboard flowchart nodes are clickable and open the details panel", () => {
  const source = fs.readFileSync(path.join(process.cwd(), "codex-phone-supervisor", "frontend", "src", "main.tsx"), "utf8");
  assert.match(source, /data-testid="codex-session-flowchart"/);
  assert.match(source, /data-testid="codex-cli-stream"/);
  assert.match(source, /stdout\/stderr piped live/);
  assert.match(source, /Codex internal logical subagents/);
  assert.match(source, /RuntimeSettings/);
  assert.match(source, /\/ready/);
  assert.match(source, /Model:/);
  assert.match(source, /Coding reasoning:/);
  assert.match(source, /Fast planning:/);
  assert.match(source, /Access:/);
  assert.match(source, /Skills:/);
  assert.match(source, /skill_inventory/);
  assert.match(source, /critical_missing/);
  assert.match(source, /Plugins:/);
  assert.match(source, /account_config_plugins/);
  assert.match(source, /Browser chat resume:/);
  assert.match(source, /data-testid="codex-browser-chat-resume"/);
  assert.match(source, /Normal terminal chat resume:/);
  assert.match(source, /codex_conversation_resume_command/);
  assert.match(source, /Rapid truthful runtime graph from live parallel Codex watcher JSON/);
  assert.match(source, /subagent advisor, Codex-chosen subagents, flowchart maker/);
  assert.match(source, /final quality check/);
  assert.match(source, /live subagent-opportunity advice/);
  assert.match(source, /vertical parallel subagent pipeline/);
  assert.match(source, /final quality-check evidence/);
  assert.match(source, /"subagent_advisor"/);
  assert.match(source, /"quality_check"/);
  assert.match(source, /parallelCircuit/);
  assert.match(source, /subagents\.length > 1 && columnCount >= 3/);
  assert.match(source, /subagentColumns\.size !== 1/);
  assert.match(source, /data-testid="parallel-agent-pipeline"/);
  assert.match(source, /Parallel Codex subagents/);
  assert.match(source, /isParallelCircuitEdge/);
  assert.match(source, /flow-arrow-parallel/);
  assert.doesNotMatch(source, /strokeDasharray: "7 5"/);
  assert.doesNotMatch(source, /data-testid="parallel-agent-lanes"/);
  assert.match(source, /hasTaskScopedLocalFlowchartNodes/);
  assert.match(source, /hasPendingSessionPlanning/);
  assert.match(source, /compactFlowchartLayout/);
  assert.match(source, /FLOW_COLUMNS = 4/);
  assert.match(source, /ResizeObserver/);
  assert.match(source, /flowColumnCount/);
  assert.match(source, /repeat\(auto-fit, minmax\(min\(100%, 420px\), 1fr\)\)/);
  assert.match(source, /flowEdgePath/);
  assert.match(source, /markerEnd="url\(#flow-arrow\)"/);
  assert.match(source, /strokeLinejoin="round"/);
  assert.match(source, /New session \+ delete project/);
  assert.match(source, /\/supervisor\/session\/reset/);
  assert.match(source, /delete_project: true/);
  assert.match(source, /data-testid="megaplan-panel"/);
  assert.match(source, /\/sessions\/\$\{encodeURIComponent\(targetSessionId\)\}\/megaplan/);
  assert.match(source, /renderMegaplanMarkdown/);
  assert.match(source, /Approve Megaplan/);
  assert.match(source, /Branch:/);
  assert.match(source, /Repo:/);
  assert.match(source, /Repo URL:/);
  assert.match(source, /megaplan\.repo\.web_url/);
  assert.match(source, /displayFlowText/);
  assert.match(source, /node\.id\.startsWith\("codex_flow:"\)/);
  assert.match(source, /node\.id\.startsWith\("codex_flow_pending:"\)/);
  assert.match(source, /flowchart_maker/);
  assert.match(source, /localFlowchartTaskId/);
  assert.match(source, /taskIds\.has\(taskId\)/);
  assert.match(source, /pendingMegaplanFlowchartTypes/);
  assert.match(source, /node\.detail\.session_id/);
  assert.match(source, /scopedFlowchartTaskIds/);
  assert.match(source, /node\.id\.startsWith\("codex_flow:"\) \|\| node\.id\.startsWith\("codex_flow_pending:"\)/);
  assert.match(source, /Codex-chosen subagents/);
  assert.match(source, /Built by one local Codex session/);
  assert.match(source, /data-testid=\{`flow-node-\$\{node\.type\}`\}/);
  assert.match(source, /onClick=\{\(\) => setSelectedNodeId\(node\.id\)\}/);
  assert.match(source, /data-testid="flow-node-details"/);
  assert.doesNotMatch(source, /C \$\{mid\}/);
  assert.doesNotMatch(source, /JSON\.stringify\(selectedNode\.detail/);
  assert.doesNotMatch(source, /Entry file/);
  assert.doesNotMatch(source, /worker-mode-selector/);
  assert.doesNotMatch(source, /Run Docker Legacy/);
  assert.doesNotMatch(source, /Run GCP VM Legacy/);
  assert.doesNotMatch(source, /Operator terminal/);
  assert.doesNotMatch(source, /\/workers/);
  assert.doesNotMatch(source, /Cloud Orchestrator/);
  assert.doesNotMatch(source, />Status<\/h2>/);
  assert.doesNotMatch(source, /Live event timeline/);
  assert.doesNotMatch(source, /Files touched/);
  assert.doesNotMatch(source, /Command failures/);
});

test("voice UI builder new app reset clears saved chat interactions", () => {
  const source = fs.readFileSync(path.join(process.cwd(), "frontend", "src", "AppBuilder.tsx"), "utf8");
  const startIndex = source.indexOf("async function startNewSession()");
  const endIndex = source.indexOf("async function loadLatestSession()");
  assert.notEqual(startIndex, -1);
  assert.notEqual(endIndex, -1);
  const resetSource = source.slice(startIndex, endIndex);
  assert.match(resetSource, /\/supervisor\/session\/reset/);
  assert.match(resetSource, /delete_project: true/);
  assert.match(resetSource, /const resetMessage: ChatMessage/);
  assert.match(resetSource, /window\.localStorage\.setItem\(interactionStorageKey, JSON\.stringify\(\[resetMessage\]\)\)/);
  assert.match(resetSource, /setChatMessages\(\[resetMessage\]\)/);
  assert.match(resetSource, /setChatInput\(""\)/);
  assert.doesNotMatch(resetSource, /setChatMessages\(\(items\) => mergeInteractions\(items/);
});
